name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - master  # Or specify any branch you want to trigger the deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use your preferred Node version

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook  # This generates the static files in the `storybook-static` directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static  # The directory where Storybook outputs static files
          publish_branch: gh-pages  # The branch for GitHub Pages, adjust if necessary
          cname: ''  # Add a custom domain if needed, leave blank for default

